apiVersion: v1
kind: Service
metadata:
  name: mc-msg-consumer
spec:
  selector:
    app: mc-msg-consumer-app
  type: NodePort
  ports:
    - port: 8086
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-msg-consumer
spec:
  selector:
    matchLabels:
      app: mc-msg-consumer-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-msg-consumer-pod
    spec:
      ports:
        - port: 8086
          nodePort: 30000
      containers:
        - name: mc-msg-consumer
          image: 192.168.1.82:32037/docker.io/mc/mc-msg-consumer:1.2.8
          ports:
            - containerPort: 8080