apiVersion: v1
kind: Service
metadata:
  name: mc-msg-consumer
  labels:
    app: mc-msg-consumer
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: mc-msg-consumer
  type: NodePort
  ports:
  - name: http-8081
    nodePort: 32030
    port: 8081
    protocol: TCP
    targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-msg-consumer
  labels:
    app: mc-msg-consumer
spec:
  selector:
    matchLabels:
      app: mc-msg-consumer-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-msg-consumer-pod
    spec:
      containers:
        - name: mc-msg-consumer
          image: 192.168.1.82:32037/docker.io/mc/mc-msg-consumer:1.8.3
          ports:
          - containerPort: 8081

---

apiVersion: v1
kind: Endpoints
metadata:
  name: mc-msg-consumer
  labels:
    app: mc-msg-consumer
subsets:
  - addresses:
      - ip: 10.244.1.157
    ports:
    - name: http-8081
      port: 8081