spring:
  kafka:
    listener:
      concurrency: 4
    bootstrap-servers: localhost:9092
    topic:
      import:
        message: import.message
        resetOffset: false
      match:
        message: match.message
        resetOffset: false
    consumer:
      group-id: mc.message